### ISSUE TITLE
potential mistake on decoding z80 opcodes

### ISSUE THREAD

**Issue by teatime-dev** [gb-archive/salvage#1]
under unprefixed opcodes, under x=3,z=0,y=4, it says `LD (0xFF00 + nn), A` as the operation.
I'm quite new to emulation but I think it's meant to say +n and not +nn since it would overflow most of the time.
Other opcode guides say n instead of nn, although perhaps for archival purposes you want might to keep this unmodified, I suppose.

**Comment by phire** [comment]
You know, I had forgotten that I had even released that file anywhere publicly. 

I'm pretty sure you are correct, +nn makes no sense. I've fixed it ["upstream"](https://github.com/phire/Kea/commit/c0d5126f144f944b6131bf3765c1e4b1ca90984e#diff-b5986f4f69a6e7c12b1bbd925af6e3e3)
